### ISSUE TITLE
Is it still an active project?

### ISSUE THREAD

**Issue by pachanga** [tumblr/jetpants#27]
Folks, jetpants looks very promising and I'd really like to use it for shards automation. Thanks! However, there haven't been any activity for an year already, so I'm wondering about current project status...

**Comment by grahamc** [comment]
Hi pachanga, Yes, Jetpants is still actively developed inside of tumblr. Sorry for taking so long to get back to you. we've been working internally on getting a release out the door. This should be happening soon :)

**Comment by grahamc** [comment]
We just pushed updates :)

**Comment by pachanga** [comment]
Thanks! I'm definitely going to have a look. However as I remember the last time I checked it the asset tracker requirement was a bit too much for us...
